odin_dust_package <- function(path, verbose = NULL, real_t = NULL,
                              int_t = NULL) {
  re_r <- "\\.R$"
  header <- "// Generated by odin.dust - do not edit"

  filenames <- dir(file.path(path, "inst/odin"), re_r, full.names = TRUE)
  if (length(filenames) == 0L) {
    stop("Did not find any files in inst/odin")
  }

  dir.create(file.path(path, "inst/dust"), FALSE, TRUE)
  ## NOTE: that mixing odin and odin.dust models together is unlikely
  ## to go well, and we assume here that all models are compilable to
  ## dust.
  options <- odin::odin_options(target = "dust", verbose = verbose)
  nms <- character()

  for (f in filenames) {
    ir <- odin::odin_parse_(f, options)
    dat <- generate_dust(ir, options, real_t, int_t)
    code <- odin_dust_code(dat, real_t, int_t)
    dest <- file.path(path, "inst", "dust", sub(re_r, ".cpp", basename(f)))
    if (file.exists(dest)) {
      txt <- readLines(dest, 1)
      if (txt != header) {
        stop("Refusing to overwrite edited file")
      }
    }
    writeLines(c(header, code), dest)
    nms <- c(nms, dat$name)
  }

  dust::dust_package(path)

  path_dust_r <- file.path(path, "R", "dust.R")
  code_r <- readLines(path_dust_r)
  code_r_index <- sprintf('%s$set("public", "index", %s)',
                          nms, paste(deparse(odin_dust_index),
                                     collapse = "\n"))
  writeLines(c(code_r, code_r_index), path_dust_r)

  path
}
